### DISCUSSION TITLE
knife4j-gateway网关聚合的场景

### DISCUSSION THREAD

**Discussion by xiaoymin** [xiaoymin/knife4j#547] [Show and tell]
网关聚合的集中场景case：

1、网关项目走Nginx代理，配置前缀，聚合时需要考虑避免basePath丢失的问题，这种情况可以在网关提供的Endpoint端口进行出来，接收Request对象，并且获取当前nginx代理过来的地址，代码示例：

```java
@GetMapping("/v3/api-docs/swagger-config")
public Mono<ResponseEntity<SwaggerV3Response>> swaggerConfig(ServerHttpRequest request) {
    String contextPath = request.getPath().contextPath().value();
    if (!StringUtils.hasLength(contextPath)) {
        contextPath = "/";
    }
}
```

2、网关聚合时，手动聚合的模式，手动聚合不用考虑子服务是那个OpenAPI规范(Swagger2/OAS3),只需要提供URL过来即可，配置如下：
```yml

knife4j:
  # 聚合swagger文档
  gateway:
    enable: true
    routes:
      - name: 用户服务
        # OpenAPI数据源，不管是Swagger/OAS3，提供地址即可聚合
        url: /user-service/v2/api-docs?group=default
        context-path: /abc
        service-name: user-service
        order: 2
      - name: 订单服务
        url: /order-service/v2/api-docs?group=default
        service-name: order-service
        order: 3

```

3、如果是通过注册中心，在Spring Cloud微服务框架下，通过服务发现的方式，自动聚合，那么需要考虑的事情：
  - 聚合的服务必须保证健康(否则前端UI会显示异常)
  -  排除网关自己(因为网关自己没有OpenAPI数据源URL接口)
  -  各个子服务需要统一OpenAPI命名规范，避免分组的情况
  -  如果有OpenAPI的分组的情况，那么需要提供解决方案
  -  子服务可能出现即包含Swagger2，也包含OAS3的情况，聚合时需要兼容

**Comment by xiaoymin** [comment]
考虑到第三点的特殊性，如果是走服务发现，那么需要有特殊要求，要求如下：

1、各个子服务必须OpenAPI规范统一，要么全部是Swagger2，要么全是OAS3

2、每一个子服务提供的OpenAPI数据源URL必须固定，不能分组，全部是`default`默认分组

**Comment by xiaoymin** [comment]
1、针对子服务可能存在分组的情况，在服务发现中增加Routes手动配置的属性，与服务发现进行Merge操作，保证能够全部聚合所有服务文档

2、另外可能还要加一个 属性，服务业务名称映射的字典配置：

a-service : 用户服务

b-service：订单服务


类似这样，但是我觉得如果子服务太多，写这个字典配置也很麻烦，不过也避免不了了

**Comment by xiaoymin** [comment]
两种模式：

第一种模式，纯手工配置(manual)
```yml
knife4j:
    enable: true
    # 指定手动配置的模式(默认为该模式)
    strategy: manual
    routes: 
        - name: 用户服务
          url: /user/v2/api-docs?group=default
          order: 1
        - name: 订单服务
          url: /order/v2/api-docs?group=default
          order: 1
 ```
 
第二种模式，基于微服务自动发现(discover)，自动聚合:

针对微服务聚合，我们有非常多的case

2.1 所有子服务全部是OpenAPI3规范
```yml
knife4j:
    enable: true
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    discover：
        enable: true
        # 指定版本号(Swagger2|OpenAPI3)
        version : openapi3
        # 需要排除的微服务(eg:网关服务)
        excluded-services:
            - gateway-service

 ```
2.2 所有子服务全部是Swagger2规范，并且是默认`default`分组
```yml
knife4j:
    enable: true
    # 指定服务发现的模式聚合微服务文档
    strategy: discover
    discover：
        enable: true
        # 指定版本号(Swagger2|OpenAPI3)
        version : swagger2
        # 需要排除的微服务(eg:网关服务)
        excluded-services:
            - gateway-service
```         

2.3     子服务中除了`default`分组，还有别的分组，测试，我们需要单独聚合(因为discover模式只聚合默认)，此时，则复用`routes`自定义属性
```yml
knife4j:
    enable: true
    # 指定服务发现的模式聚合微服务文档
    strategy: discover
    discover：
        enable: true
        # 指定版本号(Swagger2|OpenAPI3)
        version : swagger2
        # 需要排除的微服务(eg:网关服务)
        excluded-services:
            - gateway-service
    # 个性化定制的部分子服务分组情况        
    routes: 
        - name: 用户服务
          service-name: user-service
          url: /user/v2/api-docs?group=组织管理
          order: 1
        - name: 订单服务
          service-name: order-service
          url: /order/v2/api-docs?group=订单管理
          order: 1
 ```
2.4 在discover服务发现模式下，如果我们希望对聚合起来的微服务提供一些个性化配置，例如：排序、分组重命名、context-path配置等等，那么可以通过服务配置对每个服务进行配置，如下：
```yml
knife4j:
    enable: true
    # 指定服务发现的模式聚合微服务文档
    strategy: discover
    discover：
        enable: true
        # 指定版本号(Swagger2|OpenAPI3)
        version : openapi3
        # 需要排除的微服务(eg:网关服务)
        excluded-services:
            - gateway-service
        # 各个聚合服务的个性化配置，key:注册中心中的服务名称，value：个性化配置
        service-config:
            user-service:
                # 排序
                order: 1
                # 前端显示名称
                group-name : 用户服务
                # 重新指定basePath，一般在OpenAPI3规范中需要
                context-path: /user
            order-service:
                # 排序
                order: 2
                # 前端显示名称
                group-name : 订单服务
                # 重新指定basePath，一般在OpenAPI3规范中需要
                context-path: /order
 ```
