### ISSUE TITLE
关于basePath配置化的建议

### ISSUE THREAD

**Issue by Murphy-Chang** [xiaoymin/knife4j#202]
如题，由于项目的一些原因，无法在gateway网关添加swagger功能，
于是新建了一个子工程A，引用了gateway和knife4j的依赖，
从原来的网关->其他工程的/v2/api-docs变成了网关->A->其他工程的/v2/api-docs这样的调用顺序。
但是这样在调试接口前面就都存在了一个前缀“/A,/other-child”(“，”的存在是因为springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation这个方法中加进去 的，basePath的计算规则没有仔细看，不过这个不是关键)，而同时在swagger-ui中是没有这样的前缀的，所以这个前缀应该是knife4j的ui中拼接上的。
![image](https://user-images.githubusercontent.com/42343239/76743597-d643eb80-67ad-11ea-8707-8fcb1645c433.png)
![image](https://user-images.githubusercontent.com/42343239/76743634-e52a9e00-67ad-11ea-8f3d-234de1821c00.png)
前端调试的时候每次都要删掉前缀，觉得比较麻烦。
翻了翻官网也没有找到这样的配置项，所以能否提供ui上或者java上的配置。

**Comment by Murphy-Chang** [comment]
spring-cloud-gateway+knife4j2.0.2

**Comment by xiaoymin** [comment]
gateway网关凡是basePath里面带逗号的 都是和gateway本身有关系

你可以参考我的demo，https://gitee.com/xiaoym/swagger-bootstrap-ui-demo

里面是没有逗号的，另外高版本的gateway不需要加过滤请求头的配置，在application.yml里面配置的，你可以参考下

**Comment by Murphy-Chang** [comment]
好的谢谢大佬

**Comment by Murphy-Chang** [comment]
已解决
留给同样问题的同学：
gateway转发不用加前缀，https://gitee.com/xiaoym/swagger-bootstrap-ui-demo中的SwaggerHeaderFilter可以搞定

**Comment by ttimasdf** [comment]
我也遇到了这个问题，大概是网关转发给后端服务的时候产生的问题。正在尝试解决。楼上的解决方案说的比较模糊，我尝试下如果能解决，po一个更详细的解决方法

**Comment by ttimasdf** [comment]
这个问题的根源不是 Gateway 的问题，而是Gateway 后面的应用（所以也可以说是 Spring Boot 的问题？）不会正确的处理上游传过来的 `X-Forwarded-Prefix` HTTP 头，就简单的给它拼起来了。这个问题会在 gateway 前面还有其他反代，且上游反代在给 gateway 发请求的时候做了 strip prefix 且发送 `X-Forwarded-Prefix` header 的时候出现……比如我用的 traefik ，nginx 没这功能所以反而没这困扰。 

不过用楼上 `SwaggerHeaderFilter` 可以解决这个问题，就是实现个 Filter 然后加到 gateway 的 route 配置里，也不是不行。就是需要重新编译反代后面所有的业务应用。

在上游反代上去掉 `X-Forwarded-Prefix` 也可以解决问题。对应 traefik 的 compose file 配置如下。

```yml
services:
  api-gateway:
    # ...
    labels:
      - traefik.http.routers.api-gateway.rule=Host(`your-domain.com`) && PathPrefix(`/backend-api`)
      - traefik.http.routers.api-gateway.middlewares=strip-svc-path,remove-x-forwarded-prefix
      - traefik.http.middlewares.strip-svc-path.stripprefix.prefixes=/backend-api
      - traefik.http.middlewares.remove-x-forwarded-prefix.headers.customrequestheaders.X-Forwarded-Prefix=
```
