### ISSUE TITLE
请问支持geteway一个服务多个分组时，给每个分组配置扫描的包路径么？

### ISSUE THREAD

**Issue by DishJi** [xiaoymin/knife4j#468]
目前使用的knife4j-spring-boot-starter  2.0.9版本，使用的geteway微服务，每个微服务目前配置了2个分组，现在2个分组扫描的都是相同路径，不知道要怎么配置才能每个分组分配不同的包路径

**Comment by xiaoymin** [comment]
创建多个Docket对象，配置不同包路径就可以了，网关聚合的时候传递不同的分组参数名称

**Comment by xiaoymin** [comment]
例如：

```yaml
knife4j:
  # 聚合swagger文档
  gateway:
    enable: true
    routes:
      - name: 用户服务
        url: /user-service/v2/api-docs?group=default
        service-name: user-service
        order: 2
      - name: 订单服务
        url: /order-service/v2/api-docs?group=default
        service-name: order-service
        order: 3

```
> 备注：该示例来源knife4j-gateway-spring-boot-starter,参考[v4.0.0 进度issues](https://gitee.com/xiaoym/knife4j/issues/I5LIQZ)
