### ISSUE TITLE
不添加 springdoc-openapi-ui 依赖，报 Knife4j 文档请求异常

### ISSUE THREAD

**Issue by Charles7c** [xiaoymin/knife4j#517]
参照过的示例：https://gitee.com/xiaoym/swagger-bootstrap-ui-demo/blob/master/knife4j-springdoc-openapi-demo/pom.xml

### 引入依赖

```xml
    <properties>
        <knife4j.version>4.0.0</knife4j.version>
    </properties>

    <!-- 全局依赖版本管理 -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-dependencies</artifactId>
                <version>${knife4j.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
        </dependency>
    </dependencies>
```

### 添加配置

application.yml 配置

```yaml
--- ### 接口文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: ${springdoc.swagger-ui.enabled}
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.charles7c.cnadmin.webapi
## 接口文档增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
```

Java 配置：

```java
@Configuration
@RequiredArgsConstructor
@ConditionalOnProperty(name = "springdoc.swagger-ui.enabled", havingValue = "true", matchIfMissing = true)
public class SwaggerConfiguration {

    private final XXX xxx;

    /**
     * 接口文档配置
     */
    @Bean
    public OpenAPI openAPI() {
        return new OpenAPI().info(
            new Info().title(xxx.getName() + " 接口文档").version(xxx.getVersion())
                .description(xxx.getDescription()).termsOfService(xxx.getUrl())
                .contact(xxx.getAuthor()).license(xxx.getLicense()));
    }

    /**
     * 根据 @Tag 上的排序，写入 x-order
     *
     * @return the global open api customizer
     */
    @Bean
    public GlobalOpenApiCustomizer orderGlobalOpenApiCustomizer() {
        return openApi -> {
            if (openApi.getTags() != null) {
                openApi.getTags().forEach(tag -> {
                    Map<String, Object> map = new HashMap<>();
                    map.put("x-order", RandomUtil.randomInt(0, 100));
                    tag.setExtensions(map);
                });
            }
        };
    }
}
```

MVC 配置：
```java
@EnableWebMvc
@Configuration
public class WebMvcConfiguration implements WebMvcConfigurer {

    /**
     * 静态资源处理器配置
     */
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("doc.html").addResourceLocations("classpath:/META-INF/resources/");
        registry.addResourceHandler("/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/")
            .setCacheControl(CacheControl.maxAge(5, TimeUnit.HOURS).cachePublic());
    }
}
```

4.0.0 快照刚开始的时候，我就测试过，当时存在这个问题，我以为这个依赖是必须的。今天偶然在微信群里问了一嘴：看看能不能把这个依赖默认引入到 starter 中，好减少起步依赖，才知道这个依赖不是必须的。

我以为经过版本升级已经修好了，今天再次试了一下，发现若是移除下方依赖还是会报错，其实我只是需要 swagger-ui 部分的排序能力，但理论上内置的 `springdoc-openapi-webmvc-core`应该已经包含了这块配置吧？

```xml
    <dependency>
        <groupId>org.springdoc</groupId>
        <artifactId>springdoc-openapi-ui</artifactId>
    </dependency>
```
![输入图片说明](https://foruda.gitee.com/images/1671606147505398159/86b0e809_1294645.png "屏幕截图")
![输入图片说明](https://foruda.gitee.com/images/1671606154440152354/9e18f7e1_1294645.png "屏幕截图")
