### ISSUE TITLE
Basic authentication bypass

### ISSUE THREAD

**Issue by Redpeppersir** [xiaoymin/knife4j#530]
BasicFilter 中的 match函数存在绕过的风险 可以在路径中添加 /;/ 格式绕过Basic认证访问到敏感的接口
开启Basic 认证 
![image](https://user-images.githubusercontent.com/123848158/215300107-dec5ed98-18f2-4a26-b748-eb423f2754d9.png)
使用正常方式访问接口
/v2/api-docs?group=%E6%B5%8B%E8%AF%95%E5%88%86%E7%BB%84
![image](https://user-images.githubusercontent.com/123848158/215300197-5ef8035b-6dd1-4acf-928f-793a5626b8e0.png)
通过添加 ; 在不进行认证的情况下绕过接口 /v2/;/api-docs?group=测试分组
![image](https://user-images.githubusercontent.com/123848158/215300256-71ff5c9e-aba6-44e7-b425-e2877dd51be0.png)
match函数比较规避存在缺陷
![image](https://user-images.githubusercontent.com/123848158/215300064-baec9108-7dbc-4390-b8ae-36441628f000.png)
建议在获取uri的时候将”;“去除
![image](https://user-images.githubusercontent.com/123848158/215300053-d19af459-aa7d-4333-a4aa-402cf7ba63c7.png)

**Comment by xiaoymin** [comment]
最新版本吗？

**Comment by Redpeppersir** [comment]
查看的时候是最新版的 复现的时候用的demo 
最新版的应该也是可以绕过的
![image](https://user-images.githubusercontent.com/123848158/215928374-99f93951-be2f-47d9-86de-b1832aa2f2ee.png)

**Comment by Redpeppersir** [comment]
> 最新版本吗？

查看的时候是最新版的 复现的时候用的demo
最新版的应该也是可以绕过的
![image](https://user-images.githubusercontent.com/123848158/216233205-045d8111-9b8f-4f02-9370-ee3e065eb610.png)

**Comment by xiaoymin** [comment]
这个我考虑就是放开一部分match的规则(支持正则)，给开发者自己设置，不然总是会存在漏掉的
例如这样：

```yml
knife4j:
  # 开启增强配置 
  enable: true
　# 开启Swagger的Basic认证功能,默认是false
  basic:
      enable: true
      # Basic认证用户名
      username: test
      # Basic认证密码
      password: 123
      # 增加include属性，开发者自己配置，支持正则
      include:
        - /api/*
        - /v2/*

```
