### ISSUE TITLE
最新的knife4j 4版本还能支持自定义markdown文件的文档吗？

### ISSUE THREAD

**Issue by luyanfeng** [xiaoymin/knife4j#543]
springboot 3 用了最新的knife4j 4版本，还能支持自定义markdown文件的文档吗？
我之前用的springboot 2和knife4j3是可以的。

pom.xml
```xml
<dependency>
        <groupId>com.github.xiaoymin</groupId>
        <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
        <version>4.0.0</version>
</dependency>
```
application.yaml
```yaml
swagger:
  markdowns: classpath:markdown/*
```

**Comment by luyanfeng** [comment]
还有这个配置
```yaml
knife4j:
  enable: true
  cors: false
  production: false
  basic:
    enable: false
  documents:
    - group: abc
      name: Docs
      locations: classpath:markdown/*
```

**Comment by xiaoymin** [comment]
knife4j的都是knife4j的命名空间

自定义文档：

```yml
knife4j:
  documents: classpath:markdown/*

```

https://doc.xiaominfo.com/docs/features/selfdocument

4.0版本支持

**Comment by luyanfeng** [comment]
> knife4j的都是knife4j的命名空间
> 
> 自定义文档：
> 
> ```yaml
> knife4j:
>   documents: classpath:markdown/*
> ```
> 
> https://doc.xiaominfo.com/docs/features/selfdocument
> 
> 4.0版本支持

感谢回复，
我确认了下我的配置中是有这部分的，在接口里也是可以看到 x-markdownFiles 中有了，但在页面上还是看不到自定义的文档：
![image](https://user-images.githubusercontent.com/5779510/223932404-302e4116-28b3-407d-b73c-d22b1172eaea.png)

**Comment by luyanfeng** [comment]
好吧，我知道哪里出问题了：
```yaml
springdoc:
  group-configs:
    - group: abc   **// 这个group 与 knife4j.documents.group 一致才行**
      paths-to-match: '/**'
      packages-to-scan: com.lyf
```
```yaml
knife4j:
  documents:
    - group: abc                     // 这个goup
      name: Docs
      locations: classpath:markdown/*
```
