### ISSUE TITLE
接口排序问题，希望增加按method排序的配置

### ISSUE THREAD

**Issue by hemolin** [xiaoymin/knife4j#559]
在swagger中接口默认按字母顺序排序的，同时提供了swagger.ui-config.operations-sorter=method的配置来按接口方法排序。

虽然Knife4j有@ApiOperationSupport(order=int)的配置，但是接口过多时，记不清具体的数值，希望也提供按接口方法排序的配置，谢谢

**Comment by xiaoymin** [comment]
knife4j保留了官方的按 字母排序，只不过你设置的方法不对，就用官方的即可

目前springdoc有默认排序规则，如果项目中进行了设置，会按springdoc 的规则来，如下：

```yml
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

```

如果想用Knife4j的order排序，两种方案

第一种，去除operation的排序配置，如下：
```yml
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    # 注释掉该规则
    # operations-sorter: alpha
```

第二种，设置排序规则为`order`,如下：

```yml
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    # 设置规则为order，该规则会使用Knife4j的增强排序扩展规则`x-order`
    operations-sorter: order

```
