### ISSUE TITLE
#487 的排序问题在 v4.1.0 任然存在

### ISSUE THREAD

**Issue by zq99299** [xiaoymin/knife4j#570]
使用的组件包是：implementation 'com.github.xiaoymin:knife4j-openapi3-jakarta-spring-boot-starter:4.1.0'

在 #487 中的问题在，该版本中任然存在问题
<img width="942" alt="image" src="https://user-images.githubusercontent.com/11927113/236142211-4aae5c13-9fa7-4d0f-b36b-24213cc24c05.png">
如图所示

**Comment by xiaoymin** [comment]
目前springdoc有默认排序规则，如果项目中进行了设置，会按springdoc 的规则来，如下：

```yml
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

```

如果想用Knife4j的order排序，两种方案

第一种，去除operation的排序配置，如下：
```yml
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    # 注释掉该规则
    # operations-sorter: alpha
```

第二种，设置排序规则为`order`,如下：

```yml
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    # 设置规则为order，该规则会使用Knife4j的增强排序扩展规则`x-order`
    operations-sorter: order

```
