### ISSUE TITLE
4.1.0 basic 验证， 任意请求都会导致请求通过，从而导致doc.html 不提示验证

### ISSUE THREAD

**Issue by fanlisboy** [xiaoymin/knife4j#578]
使用扩展功能开启认证时
```yml
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false
  basic:
    enable: true
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: 123456
```
Knife4j-core-4.1.0.jar 包中
com.github.xiaoymin.knife4j.extend.filter.basic.ServletSecurityBasicAuthFilter
任意请求都会导致认证通过例如下图根路径，从而导致进入doc.html 不提示登录，建议修改 增加判断条件  this.match(url)

```java
public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain chain) throws IOException, ServletException {
        HttpServletRequest request = (HttpServletRequest)servletRequest;
        HttpServletResponse response = (HttpServletResponse)servletResponse;
        String url = request.getRequestURI();
        Object sessionObject = request.getSession().getAttribute("KNIFE4J_BASIC_AUTH_SESSION");
        String auth = request.getHeader("Authorization");
        if (this.tryCommonBasic(url, sessionObject, auth)) {
            if (this.match(url) && sessionObject == null) {
                request.getSession().setAttribute("KNIFE4J_BASIC_AUTH_SESSION", this.getUserName());
            }
            chain.doFilter(servletRequest, servletResponse);
        } else {
            FilterUtils.writeForbiddenCode(response);
        }
    }
```

![image](https://github.com/xiaoymin/knife4j/assets/34640448/b22f85a2-628b-40db-baee-07ece2c44ed7)
