### ISSUE TITLE
knife4j-gateway在context-path为空时, 文档显示的请求url为"//", 导致发送调试请求失败（version: swagger2）

### ISSUE THREAD

**Issue by ooooooook** [xiaoymin/knife4j#609]
**问题描述**：
![image](https://github.com/xiaoymin/knife4j/assets/28836525/4602148e-6f84-4cb0-ae00-ee3942d4f979)
knife4j-gateway在context-path为"/"时url显示为"//"导致发送调试请求

**版本**：

```xml
<dependency>
    <groupId>com.github.xiaoymin</groupId>
    <artifactId>knife4j-gateway-spring-boot-starter</artifactId>
    <version>4.1.0</version>
</dependency>
```
`knife4j-gateway 4.1.0`

**application.yml配置**：

```yaml
spring:
  application:
    name: ikuncloud-gateway
# 文档聚合
knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      version: swagger2
      excluded-services:
        - ikuncloud-gateway
```

这个BUG应该是赋予了默认的contextPath造成的，相关的断点位置：

![image](https://github.com/xiaoymin/knife4j/assets/28836525/d5f54232-873d-4d74-ab40-e8a9e004a46c)

![image](https://github.com/xiaoymin/knife4j/assets/28836525/b1bee0ac-e9ea-4033-8932-bc69d4ea6789)

或者改前端，在拼装url的时候发现contextPath为"/"时不应该将其拼接在url前面
