### ISSUE TITLE
Service name matching pattern suggestion

### ISSUE THREAD

**Issue by 4379711** [xiaoymin/knife4j#624]
### description
"service-name".equals() mode is not easy to use. 
Usually I want to exclude a lot of services. If I use `implements GatewayServiceExcludeService`, I need to modify the code frequently. I prefer to control it through the configuration file

### maven&version
```
<dependency>
    <groupId>com.github.xiaoymin</groupId>
    <artifactId>knife4j-gateway-spring-boot-starter</artifactId>
    <version>4.2.0</version>
</dependency>

<spring-boot.version>2.6.13</spring-boot.version>
<spring-cloud.version>2021.0.5</spring-cloud.version>
```

### now config
```
knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      excluded-services:
        - fatcub-gateway
        - seata-server
      version: OpenAPI3
      enabled: true
```

### expected pattern
```
knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      excluded-services:
        - *gateway
        - seata-*
      version: OpenAPI3
      enabled: true
```
