### ISSUE TITLE
[国际化] knife4j.setting.language 设置为 en-US 会报错， 但是设置为 en 可以成功

### ISSUE THREAD

**Issue by yang-ling** [xiaoymin/knife4j#636]
## 版本信息

Spring Boot: 3.1.2
knife4j-openapi3-jakarta-spring-boot-starter: 4.3.0
Java: 17

## 重现步骤

请参照复现 bug 的repo https://github.com/yang-ling/bugreport-knife4j

其 `src/main/resources/application.yml` 如果是如下配置：

``` yaml
knife4j:
  enable: true
  setting:
    language: en-US    # en-US doesn't work
    # language: en_US  # en_US doesn't work
    # language: en     # en works
```

那么执行 `./gradlew bootRun` 会报错。错误信息如下：

``` text
2023-08-15T19:12:34.756+08:00 ERROR 345193 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'knife4j.setting.language' to com.github.xiaoymin.knife4j.core.enums.OpenAPILanguageEnums:

    Property: knife4j.setting.language
    Value: "en-US"
    Origin: class path resource [application.yml] from bugreport-knife4j-0.0.1-SNAPSHOT.jar - 18:15
    Reason: failed to convert java.lang.String to com.github.xiaoymin.knife4j.core.enums.OpenAPILanguageEnums (caused by java.lang.IllegalArgumentException: No enum constant com.github.xiaoymin.knife4j.core.enums.OpenAPILanguageEnums.en-US)

Action:

Update your application's configuration. The following values are valid:

    en-US
    zh-CN
```

而如果將 `language` 设置为 `en`, 那么执行 `./gradlew bootRun` 就不会报错。
但是官方文档是要求设置为 `en-US`: https://doc.xiaominfo.com/docs/features/i18n

![](http://demo.sapicd.com/static/upload/demo/20230815/Screenshot_20230815_191702.png)
