### ISSUE TITLE
默认状态下英文名称无法正常工作

### ISSUE THREAD

**Issue by youdaocopilot** [xiaoymin/knife4j#641]
**默认状态下英文名称无法正常工作**

**To Reproduce**
我在自己的springboot项目中引入了两个依赖，
``` 
dependencies {
    implementation('org.springframework.boot:spring-boot-starter-web:2.5.3')
    implementation 'com.github.xiaoymin:knife4j-aggregation-spring-boot-starter:2.0.9'
} 
```
然后用cloud方式进行配置
```
knife4j:
  enableAggregation: true
  enable: true
  cloud:
    enable: true
    routes:
      - name: demoName
        uri: http://demo:80/
        location: /v2/api-docs
        swaggerVersion: 2.0
        order: 1
```
这种情况下前端无法正常工作，必须要把demoName改成中文才能正常工作
