### ISSUE TITLE
knife4j-gateway 服务发现自动聚合不生效

### ISSUE THREAD

**Issue by Li-Stone** [xiaoymin/knife4j#644]
**问题说明**
knife4j-gateway 服务发现自动聚合不生效
配置了spring.cloud.gateway.lower-case-service-id=true，但是在ServiceUtils.includeService中获取到的serviceName仍为大写导致匹配失败

**版本**
spring-boot: 3.1.2
knife4j-gateway-spring-boot-starter:4.3.0
spring-cloud:2022.0.4

**网关配置**
```
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  application:
    name: cloud-gateway-service

knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: OpenAPI3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8087/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
```
![image](https://github.com/xiaoymin/knife4j/assets/18192327/a2a799aa-8226-4f66-8c9e-bf9835daf0d0)
