### ISSUE TITLE
Spring Cloud Gateway 聚合后的文档没有各个微服务的前缀

### ISSUE THREAD

**Issue by HarrisonQi** [xiaoymin/knife4j#648]
**Describe the bug**
聚合后的文档没有各个微服务的前缀，需要手动添加，非常不方便

**To Reproduce**
Spring 框架版本
| 框架                | 版本         |
| --------------------- | -------------- |
| Spring Boot              | 3.0.2           |
| Spring Cloud           | 2022.0.4       |
| Spring Cloud Alibaba | 2022.0.0.0   |

gateway 服务依赖：
```xml
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-gateway-spring-boot-starter</artifactId>
            <version>4.0.0</version>
        </dependency>
```
微服务依赖：
```xml
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
            <version>4.3.0</version>
        </dependency>
```

1. 分别创建两个服务：gateway 和微服务 A
2. 在 gateway 配置 application.yml：
```yaml
knife4j:
  gateway:
    enable: true
    routes:
      - name: service-A
        url: /service-A/v3/api-docs?group=default
        service-name: 'service-A'
        order: 0
```
3. 访问 gateway:8080/doc.html
4. 切换到 微服务 A 的文档标签
5. 发现前缀未被加上

预期：`/service-A/user/create`
实际：`/user/create`

**Additional context**
该问题曾经在这里 [issues#529](https://github.com/xiaoymin/knife4j/issues/529) 反馈，但没有了下文

**Comment by HarrisonQi** [comment]
#529

**Comment by xiaoymin** [comment]
knife4j-gateway。4.3.0版本最新的

**Comment by HarrisonQi** [comment]
感谢关注该 issue！

升级至 4.3.0 后，访问 gateway 项目的 `/doc.html` 页面白屏，弹出报错提示：
<img width="1034" alt="image" src="https://github.com/xiaoymin/knife4j/assets/33210899/ed0480fa-5da5-4988-85ac-24150e0e5c36">

仔细对比区别后，发现 `4.3.0` 访问 `/swagger-resources` 会报出 404，可能是导致白屏的原因，`4.0.0` 版本无此问题。
<img width="773" alt="image" src="https://github.com/xiaoymin/knife4j/assets/33210899/51fd154a-1a64-4763-a798-9b8fec546cb3">

**Comment by HarrisonQi** [comment]
对比两个版本 pom ，发现两者分别引用了
`knife4j-openapi2-ui` 和
`knife4j-openapi3-ui` 

个人猜想：`openapi3-ui` 版本是否是漏掉了 swagger 相关的资源?

**Comment by xiaoymin** [comment]
4.3.0配置需要改一下：

```yaml
knife4j:
  gateway:
# enable换成enabled，之前合并PR的时候，不小心给改了，就懒得改回去了
    enabled: true

```

**Comment by HarrisonQi** [comment]
成功 Fix。非常感谢提供的优秀文档框架！

在这里记录一下遇到的关键节点及相应方案：

升级后，需要更改 application.yaml 的配置文件：
1. 升级 gateway:
```xml
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-gateway-spring-boot-starter</artifactId>
            <version>4.3.0</version>
        </dependency>
``` 
2. 开启 knife4j:

```yaml
knife4j:
  gateway:
    enabled: true   # 这里的key改变了
```

3. 更改微服务前缀：
```yaml
knife4j:
  gateway:
    enabled: true
    routes:
      - name: user-service
        url: /user-service/v3/api-docs?group=default
        service-name: 'user-service'
        context-path: '/user-service'     # 这里新增了 context-path, 一定要更改这里
        order: 0
```
4. 清除浏览器缓存 **非常重要** 
若不清除缓存，会一直报错404白屏
