### ISSUE TITLE
请教使用SpringDoc注解怎么实现按住ctrl多文件上传MultipartFile[]并有参数说明

### ISSUE THREAD

**Issue by TangLittle** [xiaoymin/knife4j#693]
**依赖版本:**
```xml
       <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.6.11</version>
        </dependency>

        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-spring-boot-starter</artifactId>
            <version>4.3.0</version>
        </dependency>
```
**配置**
```yml
springdoc:
  # 接口文档默认扁平化对象参数
  # 在参数对象添加校验注解@Valid或Validated时会失效 需要添加给参数对象添加@ParameterObject
  default-flat-param-object: true
```

**尝试**
```java
 @AnonymousAccess
    @Operation(summary = "批量上传")
    @PostMapping("/uploadBatch")
    public String uploadBatch(FileRequestVo fileRequestVo) {
        return "ok";
    }

    @Schema
    @Data
    private class FileRequestVo {
        // 不加@Schema注解  //knife4j中调试可以按住ctrl多选文件但没有参数说明
        // @Schema(description = "文件列表", /*implementation = MultipartFile.class, */format = "binary", required = true)  //可以单选+开启动态请求参数来实现多文件上传 但感觉没有按住ctrl多选方便
        private MultipartFile[] files;
        @Schema(description = "名称", required = true)
        private String name;
    }
```

**Expected behavior**
在knife4j中能按住ctrl多选文件并且MultipartFile[]类型的参数有参数说明
