### ISSUE TITLE
自定义文档失效

### ISSUE THREAD

**Issue by wandun** [xiaoymin/knife4j#703]
**Describe the bug**
自定义文档失效

**Screenshots**

![image](https://github.com/xiaoymin/knife4j/assets/29992863/8f2fdcc2-09e5-4ab2-997e-79a5a2f96739)

**Knife4j Version (please complete the following information):**
Knife4j 版本为 

 <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
            <version>4.3.0</version>
        </dependency>

spring Boot 版本为 3.2.0

**Additional context**

**Comment by xiaoymin** [comment]
自定义的文档`group` 这个分组名称，是和你的文档分组`default`保持一致的

示例配置如下：
```yml
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
# 这里分组名称很重要
    - group: 'default'
      display-name: '测试'
      paths-to-match: '/**'
      packages-to-scan: com.github.xiaoymin.boot3
  default-flat-param-object: true

knife4j:
  enable: true
  documents:
    - name: 标题1
      locations: classpath:markdown/*
    # 这里名称是"测试"，和上面的display-name属性保持一致
      group: 测试
```
