### ISSUE TITLE
Knife4j文档请求异常

### ISSUE THREAD

**Issue by ineptchan** [xiaoymin/knife4j#741]
**描述错误**
Knife4j文档请求异常,请求的数据是base64,并没有解码直接json反序列化

请求的url是:http://127.0.0.1:8080/v3/api-docs/default
![image](https://github.com/xiaoymin/knife4j/assets/150328571/6e09b0b3-4b28-4afa-b4de-6b791ab3a72f)
base64解码后的数据是正常的
![image](https://github.com/xiaoymin/knife4j/assets/150328571/406d3224-a772-40f2-849b-34b3a5b17dd2)

**Knife4j版本（请填写以下信息）：**
knife4j-4.4.0
Spring Boot-3.2.2
![image](https://github.com/xiaoymin/knife4j/assets/150328571/1f2d78ae-eabd-421f-ab07-e0d88a984e19)

**spring配置文件**
```yaml
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.sky.controller.admin
    - group: '用户'
      paths-to-match: '/**'
      packages-to-scan: com.sky.controller.user
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
```
