### ISSUE TITLE
knife4j-gateway-spring-boot-starter cannot support fully expanded arguments for predicates 

### ISSUE THREAD

**Issue by zpf124** [xiaoymin/knife4j#760]
**Describe the bug**
knife4j-gateway 项目对于 gateway 的配置文件写法支持不够全面，predicates 采用精简写法可以正常访问，采用完整配置写法则读取的 uri访问前缀会丢失。

**To Reproduce**
最初我配置文件中才用了 复杂写法一直页面无法访问，分析源码后发现在识别为 `GatewayRouterStrategy.CONFIG` 情况下获取前缀是只支持精简写法的。

以下配置文件中包含了两种配置写法，其中访问 `test2` 文档会报错。

``` yaml
spring:
  cloud:
    gateway:
      routes:
        - id: test-route
          uri: lb://my-test
          predicates:
            - Path=/test1/**
          filters:
            - StripPrefix=1

        - id: test2-route
          uri: lb://my-test2
          predicates:
            - name: Path
              args:
                pattern: /test2/**
          filters:
            - StripPrefix=1
```

**Expected behavior**

`ConfigRouteServiceConvert`  可以支持`spring.cloud.gateway.routes.predicates` 的完整写法。  

以下写了一个简易的例子，但我认为最好在尝试 `predicateDefinition.getArgs()` 中寻找 `pattern` 先判断 `"Path".equals(predicateDefinition.getName)`

``` java
    @Override
    String convertPathPrefix(Map<String, String> predicateArgs) {
        String value = predicateArgs.get(GatewayRouterStrategy.CONFIG.getRule());
        if (StrUtil.isNotBlank(value)) {
            return value.replace("**", StringUtil.EMPTY_STRING);
        }
       // 简易写法未读取到 path 参数时，获取尝试 获取pattern 参数
       value = predicateArgs.get(GatewayRouterStrategy.REACTIVE.getRule());
        if (StrUtil.isNotBlank(value)) {
            return value.replace("**", StringUtil.EMPTY_STRING);
        }
               return StringUtil.EMPTY_STRING;
    }
```

**Screenshots**

**Knife4j Version (please complete the following information):**
v4.5.0
