### ISSUE TITLE
当springdoc配置使用use-management-port: true的时候找不到/v3/api-docs/swagger-config

### ISSUE THREAD

**Issue by zhangzhenhuajack** [xiaoymin/knife4j#803]
有些场景下面不希望swagger-ui的端口和正常服务的端口保持一致，期望用到spring actuator的management的端口

问题复现：
````
springdoc:
  use-management-port: true 
  show-oauth2-endpoints: true
  enable-default-api-docs: true
  api-docs:
    groups:
      enabled: false
knife4j:
  enable: true
  cors: false
````
依赖jar配置如下：
````
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
            <version>4.5.0</version>
        </dependency>
````
原因是：
management的端口下面，openapi的swagger-config的地址发生了变化，而Knife4jInsightUploader.jar里面的
        String localGroup = "http://localhost:" + commonInfo.getPort() + commonInfo.getContextPath() + "/v3/api-docs/swagger-config";
        log.debug("localHost:{}", localGroup);

这段代码不支持配置，导致此功能比较悲催就报错了，找不到swagger-config
