### ISSUE TITLE
重写OperationCustomizer方法没有按我的要求自定义排序

### ISSUE THREAD

**Issue by xiwenlu** [xiaoymin/knife4j#805]
1. 版本
```
 <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
            <version>4.4.0</version>
        </dependency>
```
2. 
```
@Configuration
public class SwaggerConfig {
    @Bean
    public OperationCustomizer sortTagsOperationCustomizer() {

        List<String> orderedTags = Arrays.asList("公共接口", "首页", "登录", "商机（服务能力）", "商机（卖服务）", "服务（买服务）", "招聘", "企业管理");
        return   (operation, handlerMethod) -> {
            operation.getTags().sort(Comparator.comparingInt(orderedTags::indexOf));
            log.info("operation:{}", operation);
            return operation;
        };
    }

    @Bean
    public GroupedOpenApi defaultGroupOpenApi(OperationCustomizer sortTagsOperationCustomizer) {
        return GroupedOpenApi.builder()
                .group("default")
                .pathsToMatch("/**")
                .packagesToScan("com.antscp.module.basic.controller"
                        ,"com.antscp.module.circle.controller"
                        ,"com.antscp.module.entp.controller"
                        ,"com.antscp.module.human.controller"
                        ,"com.antscp.module.member.controller"
                        ,"com.antscp.module.resume.controller"
                        ,"com.antscp.module.service.controller"
                        ,"com.antscp.module.system.controller")
                .addOperationCustomizer(sortTagsOperationCustomizer)
                .build();
    }

}
```
3. 效果
<img width="253" alt="image" src="https://github.com/xiaoymin/knife4j/assets/39055741/f8552304-c692-41c3-8319-5548ea728cc4">

4. 没有排序

**Comment by xiwenlu** [comment]
@xiaoymin 大神帮我看看

**Comment by xiwenlu** [comment]
```
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: order
  api-docs:
    path: /v3/api-docs
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
```
