### ISSUE TITLE
接口排序不生效

### ISSUE THREAD

**Issue by 15815162480** [xiaoymin/knife4j#813]
**Knife4j Version (please complete the following information):**
4.5.0
spring boot 3.3.1

**Additional context**
已经配置
```yml
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: order
```
