### ISSUE TITLE
Cannot Show Menu Apart from Chinese Menu

### ISSUE THREAD

**Issue by g-industrialist** [xiaoymin/knife4j#835]
**Describe the bug**
According to the menu, it should be able to show English Menu, but Fail to do so now.

**To Reproduce**
1. Go to 'application.yml'
2. update the config
```yml
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn // only accept zh_cn, when I select en_US or en_us or en-US, both failed
```

3. Source code stated - OpenAPILanguageEnums (4.0.0)
```java
    EN("en-US"),
    ZH_CN("zh-CN"),
```
5. See error - running console
```bash

Update your application's configuration. The following values are valid:

    en-US
    zh-CN
```

**Expected behavior**
Should show OpenAPI in English 

**Screenshots**

**Knife4j Version (please complete the following information):**

**Additional context**
```xml
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
            <version>4.5.0</version>
```
