### ISSUE TITLE
当我设置context-path 为/api后  /api/doc.html无法访问

### ISSUE THREAD

**Issue by tri5m** [xiaoymin/knife4j#854]
版本 springBoot starter 为  4.5.0

不设置context-path可以使用`xxx/doc.html`正常访问，当设置/api后，无法通过xxx/api/doc.html访问,但是swagger-ui.html是正常的。

**Comment by hnsqls** [comment]
这样配置试试呢
```yaml
# 接口文档配置 http://localhost:8080api/doc.html
knife4j:
  enable: true  # 启用 Knife4j
  openapi:
    title: "接口文档"  # 设置文档标题
    version: "1.0"  # 设置文档版本
    group:
      default:  # 默认组配置
        api-rule: package  # 按照包扫描规则生成文档
        api-rule-resources:
          - com.ls.template.controller  # 要扫描的包路径，通常是你的控制器所在的包

server:
  port: 8080
  servlet:
    context-path: /api
```
