### ISSUE TITLE
Knife4j:4.5.0版本在Spring Boot3.3.5中应用出现的问题

### ISSUE THREAD

**Issue by ttkOfCode** [xiaoymin/knife4j#877]
-  **问题描述** 
1. No static resource v3/api-docs/swagger-config
![image](https://github.com/user-attachments/assets/428f1526-554e-47ca-9ffb-8e6c96ab8e0f)
2. 如果没有1中出现问题，就会呈现第二种问题：SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
![image](https://github.com/user-attachments/assets/ae35b101-1590-43c1-9104-e5a367c12f2d)
-  **项目中相关配置** 
1. 后端：
   > 依赖：
    ```
             <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>3.3.5</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
     <!-- knife4j-doc -->
            <dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
                <version>4.5.0</version>
            </dependency>
   
    ```
    > application.yml(第一种情况)
     ```
        springdoc:
          swagger-ui:
            enabled: false
            path: /swagger-ui.html
            tags-sorter: alpha
            operations-sorter: alpha
          api-docs:
            enabled: true
            path: /v3/api-docs/
    ```
    > application.yml(第二种情况)

    ```
        springdoc:
          swagger-ui:
            enabled: false
            path: /swagger-ui.html
            tags-sorter: alpha
            operations-sorter: alpha
          api-docs:
            enabled: true
            path: /dev-api/v3/api-docs/
    ```

> 对于第二种yml配置文件的补充说明：
显示效果
图1.Url中/dev-api前缀
![image](https://github.com/user-attachments/assets/9739d9d2-3b45-423e-a6d4-cd16ec692181)
图2.会在所有的controller接口中添加前缀/dev-api
![image](https://github.com/user-attachments/assets/6393b072-4249-49ef-adcf-13125544e5d1)
