### ISSUE TITLE
api的operationId后面多了“_1”

### ISSUE THREAD

**Issue by Jingzhenzxz** [xiaoymin/knife4j#890]
Spring Boot 2.7.14项目，
1. 依赖：
```
       <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi2-spring-boot-starter</artifactId>
            <version>4.4.0</version>
        </dependency>
```
2. application.yml中的配置：
```
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.xx.xx.xx.controller
```
3. 启动应用，访问 http://localhost:8087/api/v2/api-docs 发现每个 api 的 operationId 后面都多了“_1”，例如
![Image](https://github.com/user-attachments/assets/37c0c115-5e7f-4aa4-844d-99f693664f04)

4. 接口代码如下
```
@RestController
@RequestMapping("/media")
public class MediaController {
    @GetMapping("/getById/vo")
    public BaseResponse<MediaVO> getMediaVOById(@RequestParam Long id, HttpServletRequest request) {

    }
```

请问这是怎么回事？
