### ISSUE TITLE
访问文档接口初始化报错

### ISSUE THREAD

**Issue by lijianguo1211** [xiaoymin/knife4j#910]
spring-boot版本为：
`<spring-boot-version>3.4.5</spring-boot-version>`
knife4j的版本为：
`<knife4j-version>4.5.0</knife4j-version>`

具体的引入POM为：
```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
        </dependency>
```
配置文件为：
```yaml
springdoc:
  group-configs:
    - group: test1
      packages-to-scan: com.baidu.product.api
      paths-to-match:
        - /**
  api-docs:
    enabled: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
```

访问文档地址之后，接口报错：

![Image](https://github.com/user-attachments/assets/848476a9-9c66-4a16-bf72-bdcca8e3a525)

![Image](https://github.com/user-attachments/assets/3c5c01b9-9e9a-4505-8aa2-d75b7a88bc9a)

![Image](https://github.com/user-attachments/assets/fb74781f-6686-4a9d-ac0a-6aee1c0b283c)

![Image](https://github.com/user-attachments/assets/888f42c3-2ea1-4738-abed-03925d01f0b2)

![Image](https://github.com/user-attachments/assets/d970c5ba-0b17-40f5-9e9f-4a8d3f1f3521)
